# Generated by Django 4.2.6 on 2023-10-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('numero_colegiado', models.IntegerField()),
                ('especialidad', models.CharField(max_length=64)),
                ('diagnostico', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('dpi', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=128)),
                ('razon_de_visita', models.CharField(max_length=128)),
                ('receta_medica', models.CharField(max_length=128)),
                ('numero_telefonico', models.IntegerField()),
            ],
        ),
    ]
