# Generated by Django 4.2.6 on 2023-11-12 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('numero_colegiado', models.CharField(max_length=64)),
                ('especialidad', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('dpi', models.CharField(max_length=64)),
                ('fecha_de_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=128)),
                ('numero_telefonico', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.CharField(max_length=128)),
                ('receta_medica', models.CharField(max_length=128)),
                ('razon_de_visita', models.CharField(max_length=128)),
                ('cita_hecha', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
            ],
        ),
    ]
